### PR TITLE
Add single-attempt timed retry to CSRF token fetch

### PR DESCRIPTION
**Pull request by SorenSpicknall**
Hey y'all, apologies for the unsolicited PR.

I have an email out to some New/Mode folks (Ben and Mikey, specifically) about an issue we've been having at TMC where the API doesn't always fetch a CSRF token correctly when doing rapid-fire calls. We're waiting to hear back, and I'm happy to close this PR if the issue turns out to be something on our end, but I thought it might be helpful to build a single-time retry logic into the CSRF token fetch in order to avoid the problems we're seeing in practice.

Let me know if I can clarify the intent here, or expand on what's happening unexpectedly when the existing code is in use here at TMC.

### CODE REVIEW

**Comment by SorenSpicknall** [comment]
Adding a little bit more context here: an alternative workable solution (and perhaps a preferable one for some users) would be to surface the full response in the return of every function, even if the status code is not 200. The trouble we're running into at the moment is that it's impossible to add precise retry logic in our own client code, since non-200 responses result in logging with nothing returned.

Since our particular issue had to do with lost CSRF tokens, I attempted to mitigate that issue in the token getter, but it might also be good to take a broader approach closer to where client calls are made in the code.

**Comment by yi-yang-github** [comment]
I believe the change doesn't make too much sense. Not sure what exactly is your problem but maybe your request doesn't really need CSRF token? getCSRF token is called in
```
    def baseRequest(self, endpoint, method='GET', payload={}, supports_version=True, requires_csrf=True, params={}):
        # Internal Request Method
        url = self.api_url
        if supports_version:
            url += self.api_version + '/'
        url += endpoint
        headers = {
            'Content-Type': "application/json"
        }
        if (requires_csrf):
            csrf = self.getCSRFToken()
            headers["X-CSRF-Token"] = csrf
...
```
And requires_csrf can be FALSE (actually for GET requests, requires_csrf should be FALSE)

**Comment by mirabuck** [comment]
Thanks for your work here @SorenSpicknall.  We're keen to work with you to make any adjustments that may be necesary.  Answers to Yi's questions abouve should help us ensure that the correct changes get made if necessary.

**Comment by SorenSpicknall** [comment]
Thanks for the replies; I appreciate your thoughts.

I'm self-closing this for now. This small workaround was suggested in the midst of an immediate issue that I didn't have much diagnostic information about, but after chatting with some New/Mode folks via email, it looks like we're on a path to figure out the underlying failure behind the CSRF fetch issues we're facing over here at TMC in a more private setting, and figure out solutions from there. I'm still supportive of surfacing full error responses in addition to logging failures, which I discussed in my first comment, but the code changes to enable that would be so substantially different than the changes in this PR that I think it would be best to contain them in a separate PR.

**Pull request closed without merging**
